import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import Box from "../src/components/atoms/Box";
import MainFrame from "../src/components/organisms/MainFrame";
import { DataState } from "../src/context/DataContext";

export default function Home({ popularMovies }: any) {
  return (
    <DataState>
      <Head>
        <meta name="viewport" content= "width=device-width, user-scalable=no"/>
      </Head>
      <Box styles={styles.container}>
        <Head>
          <title>MovieZone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
          />
        </Head>
        <MainFrame initialData={popularMovies} />
      </Box>
    </DataState>
  );
}

export async function getServerSideProps(context: any) {
  const API_KEY = "d4c03f4129a308e4d7ce300cedccd125";
  const popularMoviesResponse = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=${API_KEY}&language=en-US&page=1`
  );
  const popularMoviesData = await popularMoviesResponse.json();
  console.log("Popular Movies are retreived before page load.");
  return { props: { popularMovies: popularMoviesData } };
}
